### ISSUE TITLE
invalid-request: el campo hash es inválido

### ISSUE THREAD

**Issue by franciscocastrovera** [khipu/lib-dotnet#1]
Copié el código de ejemplo para "2) Crear cobros y enviarlos por mail.", puse mis credenciales, ejecuté y obtuve:

invalid-request
El campo hash es inválido

Donde va el hash? no lo cálcula la libreria?

**Comment by amillalen** [comment]
Hola Francisco,
Efectivamente la librería hace el cálculo del hash.
¿Puedes darme el id de cobrador que utilizaste para verificar el caso?

**Comment by franciscocastrovera** [comment]
Hola

Este es el id: 38603. 

Probé luego la creción de url de pago y esta si me funciona sin problemas.

Saludos

**Comment by amillalen** [comment]
Hola Francisco,

Gracias por la información. Efectivamente el problema está en la librería, y solo se presenta al generar un cobro por correo.
La versión corregida ya se encuentra liberada como v1.0.1 en github. También se subió una nueva versión del paquete NuGet con la corrección.

Muchas gracias.
